### ISSUE TITLE
Fix ExNavigator Buttons

### ISSUE THREAD

**Issue by jonahgeorge** [house-homies/client#5]

**Comment by glitteringkatie** [comment]
This should have been fixed 3 days ago with this commit: https://github.com/house-homies/client/commit/e75f5b40062743b3d6830bf81a8314030da81a8f
And I see the changes represented here in the form of added styles: https://github.com/house-homies/client/blob/master/app/Router.js

@jonahgeorge Let me know if this isn't what you were seeing or thinking but as per my interpretation of this, I am closing this issue

**Comment by jonahgeorge** [comment]
Yup, all of your changes are in place. Must not have noticed them when I merged in. Thanks! 🙌
